apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker-server
spec:
  replicas: 1
  selector:
    matchLabels:
        app: worker-server
  template:
    metadata:
      labels:
        app: worker-server
    spec:
      containers:
      - name: worker-server
        image: gcr.io/lab7-490321/demucs-worker:v1
        imagePullPolicy: Always
        # Override any image ENTRYPOINT so our script is the main process
        command: ["python3", "worker-server.py"]
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: MINIO_HOST
          value: "minio:9000"
