apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-deployment
  labels:
    app: rest-server
spec:
  replicas: 1
  selector:
    matchLabels:
        app: rest-server
  template:
    metadata:
      labels:
        app: rest-server
    spec:
      containers:
      - name: rest-server
        image: gcr.io/YOUR_PROJECT_ID_HERE/demucs-rest:v1
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: MINIO_HOST
          value: "minio-proj"
---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: rest-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
spec:
  defaultBackend:
    service:
      name: rest-service
      port: 
        number: 5000
